### ISSUE TITLE
Undefined core-js dependency

### ISSUE THREAD

**Issue by richardowen** [sebastian-software/app-manifest-loader#1]
When downloaded from NPM, this package appears to require `core-js`. At the top of `lib/app-manifest-loader.js`, there are lines such as:

`require('core-js/modules/es6.array.map');`

`core-js` isn't defined as a dependency of this package and so this is breaking when I run webpack. This has only just started affecting my project as previously I was using `webpack-cli` v2 which depended on `core-js`. Now that I've upgraded to `webpack-cli` v3, it no longer has that dependency, so `core-js` is no longer installed and this package breaks.

Installing `core-js` fixes the issue so I would suggest this needs to be added to the package dependencies.

**Comment by swernerx** [comment]
You are right. I’ll fix it ASAP.

**Comment by swernerx** [comment]
Should be fixed with 1.0.4.

**Comment by richardowen** [comment]
Looks good, thanks! 👍
